language: java
deploy:
  provider: heroku
  api_key:
    secure: LyfoDd99N70FM3G9dnnmiMDgVZj17Evc2t7lUQQFHlJU8IVmoNI23BzuDUzlO4py2YMADmnE8pqWyF4+vuE+WLVH1KIMAhccHUCtuPgkl33tcCGHgnbVnw+iV5axwj1ONSGwO6cKqAtnKXNe1EeLF/emxfKNFFcmp5nqoAnRs7dr3UZCX6g2pHR1VE5l2IF1Icaslwc+TOD4y4Wd4bqaGyvWqKtk29aSfQ9rQnkgIXvY4jfT2I2PdKj4Xit4WR6JtD7H5yz4+yUhxvHjwlu12szSXv6lsOBE7MSYeVNsG6E6OiB14OWUpjOJsIRmOmWU967ONI7R7zoRan3X+SeT8oLMrMo/mTWIOcZvpbwv6qOg1G2ugZ+q0EcdLkHPmoKGjqeDAy3O0tbSYyVnXkszRcLj3T4SgMqyqB6l864iY7J5oTFq8oISnXUM5yAh1DEbME1s1ot3xiQ9eusm5z1GofifEOAXPp2Da280uE2z5hvZCbrPDwM8MvisDQKyobawCyTggeCCgIN0ggtIrRRrRH13DP+3iBaqGVUg1hzuSyVkwQOXWPm3soXw1h3RdODMSPAGM8PFXJ+3JWY1S9nY2mcA6YwhQ802uEtDT6jFqy2srZBqsCVtizedLQwZalel8Nlc6WDrKKZ9zdNsSq5CA/eI6KzGvexkLk8VSVp1aJY=
  app: hello
